server:
  port: 8090
spring:
  application:
    name: zipkinclient
  sleuth:
    web:
       client:
         enable: true
    sampler:
      probability: 1.0
  zipkin:
    base_url: http://localhost:9090/
eureka:
  client:
   service-url:
    defaultZone: http://localhost:8761/eureka

#`spring.sleuth.web.client.enabled`：设置开启请求跟踪
#`spring.sleuth.sampler.probability`：设置采样比例，默认是 1.0
#`srping.zipkin.base-url`：Zipkin Server 地址